let name = "Tusar Mondal";
let school = "St. Mary's English School";
let grade = "A+";
let section = "A";
let rollno = 3;
let maths = 95;
let english = 85;
let science = 90;

console.log("\n*************************************");
console.log("! Name: " + name + "\t\t\t\t!");
console.log("! School: " + school + "\t!");
console.log("! Grade: " + grade + "\t\t\t\t\t\t\t!");
console.log("! Section: " + section + "\t\t\t\t\t\t!");
console.log("! Roll no.: " + rollno + "\t\t\t\t\t\t!");
console.log("*************************************");
console.log("!\t\t\t\t\t\t\t\t\t!");
console.log("!\t\t +-----------------+\t\t!");
console.log("!\t\t |Subjects    Marks|\t\t!");
console.log("!\t\t |-----------------|\t\t!");
console.log("!\t\t | Maths        " + maths + " |\t\t!");
console.log("!\t\t | English      " + english + " |\t\t!");
console.log("!\t\t | Science      " + science + " |\t\t!");
console.log("!\t\t +-----------------+\t\t!");
console.log("!\t\t\t\t\t\t\t\t\t!");
console.log("*************************************\n");